spring:
  application:
    name: api-gateway
    
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: catalog-service
        uri: http://localhost:3030
        predicates:
        - Path=/api/v1/catalogs/** 
        
      - id: passenger-service
        uri: http://localhost:9090
        predicates:
        - Path=/api/v1/passengers/** 
                 

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        
server:
  port: 8080