spring:
  datasource:
    url: jdbc:oracle:thin:@10.90.1.107:1521/SIT
    username: HR
    password: HR
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update
server:
  port: 9090   