server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lakshmipriyabj/Testing.git 
          serch-paths:
          - '{application}'
          
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"          
           